qcacld-3.0: Fix compilation issue from dp_affn_override_cfg_init
Change function to static inline to avoid below failure.

wlan_dp_main.c:1359:6: error: no previous prototype for
'dp_affn_override_cfg_init' [-Werror=missing-prototypes]
 1359 | void dp_affn_override_cfg_init(
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I82803ab0dba51dc61e360122d050d0f0e96b8d92
CRs-Fixed: 4330893